apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: app=ghcr.io/godsvictory/app
    argocd-image-updater.argoproj.io/app.update-strategy: latest
  name: app-dev
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: app-dev
    server: {{ .Values.spec.destination.server }}
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
  source:
    path: helm
    repoURL: https://github.com/GodsVictory/app
    targetRevision: HEAD
    helm:
      valueFiles:
      - values-dev.yaml
