apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-prod
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: app-prod
    server: {{ .Values.spec.destination.server }}
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
    - Prune=true
  source:
    path: helm
    repoURL: https://github.com/GodsVictory/app
    targetRevision: v1.1.2
    helm:
      valueFiles:
      - values-prod.yaml
      parameters:
      - name: "image.tag"
        value: $ARGOCD_APP_SOURCE_TARGET_REVISION
