apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: xyz-{{ .Values.env }}
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: xyz-{{ .Values.env }}
    server: {{ .Values.spec.destination.server }}
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
  source:
    path: helm
    repoURL: https://github.com/GodsVictory/abc.git
    targetRevision: {{ get .Values.xyz.versions .Values.env}}
    helm:
      valueFiles:
      - values-{{ .Values.env }}.yaml
      parameters:
      - name: "image.tag"
        {{- if eq .Values.env "dev" }}
        # this variable is the latest git commit hash as the override for the apps helm chart image tag
        value: $ARGOCD_APP_REVISION
        {{- else }}
        value: {{ get .Values.xyz.versions .Values.env}}
        {{- end }}
      - name: "ingress.hosts"
        value: "{ {{ .Values.env }}.xyz.local }"
